version: '3.8'
services:
  prisma-migrate:
    build:
      context: .
      dockerfile: ./apps/api/prisma/Dockerfile
    container_name: prisma-migrate
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - backend
    restart: "no"
