version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: api
    networks:
      - proxy
    environment:
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      DISCORD_API_CLIENT_ID: ${DISCORD_API_CLIENT_ID}
      DISCORD_API_CLIENT_SECRET: ${DISCORD_API_CLIENT_SECRET}
      FT_API_CLIENT_ID: ${FT_API_CLIENT_ID}
      FT_API_CLIENT_SECRET: ${FT_API_CLIENT_SECRET}
      SESSION_PASSWORD: ${SESSION_PASSWORD}
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: web
    depends_on:
      - api
    networks:
      - proxy
    environment:
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      DISCORD_API_CLIENT_ID: ${DISCORD_API_CLIENT_ID}
      FT_API_CLIENT_ID: ${FT_API_CLIENT_ID}
      SESSION_PASSWORD: ${SESSION_PASSWORD}
    restart: unless-stopped

  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    depends_on:
      - web
    ports:
      - 8080:80
    volumes:
      - ./templates:/etc/nginx/templates
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
